import streamlit as st
import os, base64, time
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from gtts import gTTS
from PIL import Image
import google.generativeai as genai

# 🔱 [PHASE 1: THE GEMINI INTERFACE]
st.set_page_config(page_title="RAJA AI 👑", layout="wide")

# CSS: Gemini जैसा क्लीन और डार्क लुक
st.markdown("""
    <style>
    /* Background & Font */
    html, body, [data-testid="stAppViewContainer"] {
        background-color: #131314 !important;
        color: #e3e3e3 !important;
        font-family: 'Google Sans', sans-serif;
    }
    
    /* Header (Raja AI with Crown) */
    .header-text {
        font-size: 40px; font-weight: bold; text-align: center;
        color: #FFD700; margin-top: 20px; letter-spacing: 2px;
    }

    /* Gemini Chat Bubbles */
    .stChatMessage {
        background-color: transparent !important;
        border: none !important;
    }
    
    /* Custom Input Area (Fixed at bottom) */
    div[data-testid="stChatInput"] {
        border-radius: 30px !important;
        background-color: #1e1f20 !important;
        border: 1px solid #444746 !important;
    }
    
    /* Global Globe Style */
    .globe-box {
        border: 1px solid #FFD700; border-radius: 20px;
        box-shadow: 0 0 20px rgba(255, 215, 0, 0.2);
    }
    </style>
    <div class="header-text">👑 RAJA AI 👑</div>
""", unsafe_allow_html=True)

# 🔱 [PHASE 2: ENGINES INITIALIZATION]
class RajaEngine:
    def __init__(self):
        self.GROQ_KEY = st.secrets.get("GROQ_API_KEY")
        self.GEMINI_KEY = st.secrets.get("GEMINI_KEY")
        if self.GEMINI_KEY:
            genai.configure(api_key=self.GEMINI_KEY)

    def speak_response(self, text):
        tts = gTTS(text=text[:300], lang='hi')
        tts.save("audio.mp3")
        with open("audio.mp3", "rb") as f:
            data = base64.b64encode(f.read()).decode()
        st.markdown(f'<audio autoplay src="data:audio/mp3;base64,{data}">', unsafe_allow_html=True)

raja = RajaEngine()

# 🔱 [PHASE 3: GLOBAL INTELLIGENCE MAP]
# बीच में घूमता हुआ ग्लोब (जैसे Gemini का लोडिंग या डेटा विजुअल)
st.markdown("<div class='globe-box'>", unsafe_allow_html=True)
st.image("https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJndXo3NXo4bmR2bmR2bmR2bmR2bmR2bmR2bmR2bmR2bmR2JmVwPXYxX2ludGVybmFsX2dpZl9ieV9pZCZjdD1n/3o7TKMGpxVfNV3V4re/giphy.gif", use_container_width=True)
st.markdown("</div>", unsafe_allow_html=True)

# 🔱 [PHASE 4: PERSISTENT CHAT HISTORY]
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

for chat in st.session_state.chat_history:
    with st.chat_message(chat["role"]):
        st.write(chat["content"])

# 🔱 [PHASE 5: MULTI-MODAL INPUT (+ BUTTON)]
# Gemini की तरह फ़ाइल अपलोड और टेक्स्ट इनपुट
with st.container():
    col1, col2 = st.columns([1, 10])
    with col1:
        # "+" का काम करने वाला अपलोडर
        file_input = st.file_uploader("➕", type=['jpg', 'png', 'jpeg', 'mp4'], label_visibility="visible")
    
    user_query = st.chat_input("Ask RAJA AI...")

# 🔱 [PHASE 6: REASONING & OUTPUT]
if user_query or file_input:
    # यूजर का मैसेज दिखाओ
    if user_query:
        st.session_state.chat_history.append({"role": "user", "content": user_query})
        with st.chat_message("user"):
            st.write(user_query)

    with st.chat_message("assistant"):
        response_text = ""
        
        # 1. PHOTO ANALYSIS (फोटो देखना)
        if file_input and file_input.type.startswith('image'):
            img = Image.open(file_input)
            st.image(img, caption="Analyzing Image...", width=400)
            vision_model = genai.GenerativeModel("gemini-1.5-flash-latest")
            res = vision_model.generate_content([user_query if user_query else "इस फोटो का वर्णन करें", img])
            response_text = res.text

        # 2. IMAGE/VIDEO GENERATION (फोटो/वीडियो बनाना)
        elif user_query and any(x in user_query.lower() for x in ["बनाओ", "create", "generate", "image", "video"]):
            with st.spinner("🎨 Creating..."):
                img_url = f"https://image.pollinations.ai/prompt/{user_query.replace(' ','%20')}?model=flux&nologo=true"
                st.image(img_url, caption="Generated by RAJA AI")
                response_text = "🔱 आपके हुक्म पर यह रचना तैयार है, राजाराम भाई!"

        # 3. SUPREME CHAT (Llama 405B)
        else:
            with st.spinner("🧠 Thinking..."):
                llm = ChatGroq(groq_api_key=raja.GROQ_KEY, model_name="llama-3.1-405b-reasoning")
                res = llm.invoke([SystemMessage(content="You are RAJA AI. Supreme Intelligence.")] + 
                                 [HumanMessage(content=user_query)])
                response_text = res.content

        st.write(response_text)
        st.session_state.chat_history.append({"role": "assistant", "content": response_text})
        
        # आवाज़ में जवाब (Face to Face vibe)
        raja.speak_response(response_text)

# 🔱 [PHASE 7: FACE-TO-FACE CAMERA]
if st.button("🎥 Start Face-to-Face Mode"):
    st.camera_input("Raja AI is looking at you...")
